# 3.3 파이토치에서의 경사하강법

In [1]:
import torch

In [2]:
X = torch.Tensor(2, 3)

In [3]:
X

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [6]:
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
# requires_grad : 이 텐서에 대한 기울기를 저장할지 여부
x_tensor = torch.tensor(data=[2.0, 3.0], requires_grad=True)

$z=2x^2 + 3$라는 식에서 $x$의 기울기를 구하는 코드<br>

In [9]:
import torch

# x라는 텐서 생성하며 기울기를 계산하도록 지정
x = torch.tensor(data=[2.0, 3.0], requires_grad=True)
y = x**2
z = 2*y + 3

target = torch.tensor([3.0, 4.0])
loss = torch.sum(torch.abs(z-target))

# 연산 그래프를 쭉 따라가면서 잎노드 x에 대한 기울기 계산
loss.backward()

print(x.grad, y.grad, z.grad)

tensor([ 8., 12.]) None None


선형회귀분석 모델을 만들어서 기울기를 계산하고 w, b를 업데이트하는 코드

In [10]:
import torch

# 신경망 모델 포함
import torch.nn as nn
# 경사하강법 알고리즘 포함
import torch.optim as optim
# 텐서에 초깃값을 주기 위해 필요한 함수 포함
import torch.nn.init as init

# 데이터 수
num_data = 1000
# 경사하강법 반복 횟수
num_epoch = 500

# x라는 변수에 [num_data, 1] 모양의 텐서를 생성
# 텐서의 값들을 init.unifotm_()이라는 함수로 -10부터 10까지 균등하게 초기화
x = init.uniform_(torch.Tensor(num_data, 1), -10, 10)
noise = init.normal_(torch.FloatTensor(num_data, 1), std=1)
y = 2*x + 3
y_noise = 2*(x+noise)+3

model = nn.Linear(1, 1)
loss_func = nn.L1Loss()

optimizer = optim.SGD(model.parameters(), lr=0.01)

label = y_noise
for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_func(output, label)
    loss.backward()
    optimizer.step()
    
    if i % 10 == 0:
        print(loss.data)
        
param_list = list(model.parameters())
print(param_list[0].item(), param_list[1].item())

tensor(14.5690)
tensor(12.3515)
tensor(10.1835)
tensor(8.1505)
tensor(6.2707)
tensor(4.8174)
tensor(4.1206)
tensor(3.8030)
tensor(3.6123)
tensor(3.4820)
tensor(3.3758)
tensor(3.2826)
tensor(3.1989)
tensor(3.1201)
tensor(3.0454)
tensor(2.9722)
tensor(2.9012)
tensor(2.8341)
tensor(2.7696)
tensor(2.7073)
tensor(2.6474)
tensor(2.5895)
tensor(2.5328)
tensor(2.4778)
tensor(2.4247)
tensor(2.3739)
tensor(2.3259)
tensor(2.2812)
tensor(2.2384)
tensor(2.1981)
tensor(2.1595)
tensor(2.1229)
tensor(2.0890)
tensor(2.0572)
tensor(2.0265)
tensor(1.9970)
tensor(1.9684)
tensor(1.9411)
tensor(1.9152)
tensor(1.8907)
tensor(1.8676)
tensor(1.8461)
tensor(1.8264)
tensor(1.8085)
tensor(1.7916)
tensor(1.7756)
tensor(1.7613)
tensor(1.7477)
tensor(1.7348)
tensor(1.7225)
2.0042219161987305 2.1095597743988037
